# Generated by Django 5.2.8 on 2025-12-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0003_remove_payroll_deductions_payroll_allowances_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
